name: Delete Release

on: delete
jobs:
  delete:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Delete Release
        uses: cb80/delrel@latest
        with:
          tag: latest

      - name: Revert Release Commit
        run: |
          git fetch origin
          git checkout origin/gh-pages
          git checkout -b gh-pages
          git revert --no-edit $(git rev-parse :/"Update index.yaml to contain latest release: ${{ github.event.ref }}")
          git commit --amend -m "Revert Release ${{ github.event.ref }}"
          git push origin gh-pages
