name: Release Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Create Helm package
        run: helm package ./charts/cortex-agent

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cortex-xdr*.tgz

      - name: Commit new index.yaml
        run: |
          git fetch origin
          git checkout origin/gh-pages
          git checkout -b gh-pages
          helm repo index . --url https://github.com/${{ github.repository }}/releases/download/${GITHUB_REF#refs/tags/} --merge index.yaml
          git add index.yaml
          git commit -m "Update index.yaml to contain latest release: ${GITHUB_REF#refs/tags/}"
          git push origin gh-pages
